baseURL = 'http://kqx.io'
theme = 'risotto'
title = "kqx"
author = 'leave & prosti'
languageCode = 'en-us'
DefaultContentLanguage = "en"
enableInlineShortcodes = true
# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[pagination]
pagerSize = 3

[params]
noindex = false

[params.theme]
palette = "base16-dark"

# Sidebar: about/bio
[params.about]
title = "kqx"
# unicode/emoji logo:
logo = "</>"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 6 <https://fontawesome.com/> ('fa-brands', 'fa-normal', or 'fa-solid' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.users]]
name = "Erge"

  [[params.users.socialLinks]]
    icon = "fa-brands fa-discord"
    title = "Discord"
    url = "erge06"

  [[params.users.socialLinks]]
    icon = "fa-brands fa-github"
    title = "GitHub"
    url = "https://github.com/Lobsterge"

  [[params.users.socialLinks]]	
    icon = "fa-solid fa-envelope"
    title = "Email"
    url = "mailto:erge894@gmail.com"

[[params.users]]
name = "leave"

  [[params.users.socialLinks]]
    icon = "fa-brands fa-discord"
    title = "Discord"
    url = "leave07"

  [[params.users.socialLinks]]
    icon = "fa-brands fa-github"
    title = "GitHub"
    url = "https://github.com/manuele-pandolfi"

  [[params.users.socialLinks]]
    icon = "fa-brands fa-x-twitter"
    title = "X"
    url = "https://x.com/_leave07"

  [[params.users.socialLinks]]
    icon = "fa-solid fa-envelope"
    title = "Email"
    url = "mailto:manuele.pand@gmail.com"

[[params.users]]
name = "prosti"

  [[params.users.socialLinks]]
    icon = "fa-brands fa-discord"
    title = "Discord"
    url = ".prosti."

  [[params.users.socialLinks]]
  icon = "fa-brands fa-github"
  title = "GitHub"
  url = "https://github.com/GabrielProstitis"

  [[params.users.socialLinks]]
  icon = "fa-brands fa-x-twitter"
  title = "X"
  url = "https://x.com/___prosti"

  [[params.users.socialLinks]]
  icon = "fa-solid fa-envelope"
  title = "Email"
  url = "mailto:prostitisgabriel@gmail.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

	[[menu.main]]
    identifier = "writeups"
    name = "Writeups"
    url = "/writeups/"
    weight = 0

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[markup]

  # Table of contents
  # Add toc = true to content front matter to enable
  [markup.tableOfContents]
    startLevel = 2
    endLevel   = 3
    ordered    = true

# For github pages
[caches]
  [caches.images]
    dir = ':cacheDir/images'